### ISSUE TITLE
Add an Alias to an Asset

### ISSUE THREAD

**Issue by aleixmorgadas** [nemfoundation/nem2-wallet-browserextension#4]
Depends on #2 #3.

In the Asset Managament tab, on the assets I own, I should be able to attach a namespace I own as an alias.

**Acceptance Criteria:**
```
Given an asset I own
And a namespace I rented,
When I attach the namespace to the asset,
Then the asset has the namespace as an alias
```

**Comment by decentraliser** [comment]
i'll do it tomorrow morning, together with modify asset

**Comment by decentraliser** [comment]
the `mosaicInfo` model is not yet including the alias property of a mosaic. This is due to a current limitation of catapult-rest. Will have to update when it is upgraded.

[reference](https://nem2.slack.com/messages/CEZKUE4KB/convo/CEZKUE4KB-1555328152.054200/)
